#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

set -x

def=l7mp-openapi.yaml
cp ../openapi/$def .
note="$(git describe --dirty --always --tags) ($(date -I))"

docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v4.3.1 generate \
    -i /local/$def \
    -g python \
    -o /local/out \
    --package-name l7mp_client \
    --release-note "$note"
