#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BUILD_ARGS=$@

set -x
cd "$DIR"
version=$(sed -ns '1,30s/.*version: \(.*\)/\1/p' l7mp.py)

name=l7mp/l7mp-operator

../openapi/convert-schema -i ./crd.template.yml -o crd.yml -t k8s
../openapi/convert-schema -i ./crd.template.yml -o conv.yml -t old

cp -r ../python-client/out/l7mp_client .
cp ../python-client/out/requirements.txt .

cat <<EOF >>requirements.txt
pyyaml
kubernetes
pykube-ng
grpcio
numpy
futures
protobuf
xds-protos
EOF

docker build $BUILD_ARGS . -t $name:$version -t $name:latest
