# Controller listening on 1234, plus some useful debug clusters
admin:
  log_level: info
  log_file: stdout
  access_log_path: /tmp/admin_access.log
listeners:
  - name: controller_listener
    spec: { protocol: HTTP, port: 1234 }
    rules:
      - action:
          route:
            destination: l7mp-controller
  - name: udp-listener
    spec: { protocol: UDP, port: 15000 }
    rules:
      - action:
          route:
            destination:
              spec: { protocol: UDP, port: 16000 }
              endpoints:
                - name: receiver
                  spec: { address:  "127.0.0.1"}
            ingress:
              - udp-ingress-metric-counter
            egress:
              - udp-egress-metric-counter
  - name: prometheus_listener
    spec: { protocol: HTTP, port: 8080 }
    rules:
      - name: rule-prom
        match: {op: starts, path: '/HTTP/url/path', value: '/metrics'}
        action:
          route:
            destination: prometheus-cluster
clusters:
  - name: l7mp-controller
    spec: { protocol: L7mpController }
  - name: prometheus-cluster
    spec: { protocol: Prometheus }
  - name: udp-ingress-metric-counter
    spec: { protocol: Metric }
  - name: udp-egress-metric-counter
    spec: { protocol: Metric }