apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
