{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.selectorLabels.component }}
    app.kubernetes.io/name: {{ .Values.selectorLabels.name }}
    app.kubernetes.io/version: {{ .Values.selectorLabels.version }}
{{- end }}
