apiVersion: v1
kind: ConfigMap
metadata:
  name: l7mp-ingress
data:
  l7mp-ingress.yaml: |
    admin:
      log_level: info
      log_file: stdout
      access_log_path: /tmp/admin_access.log
    listeners:
      - name: controller-listener
        spec: { protocol: HTTP, port: 1234 }
        rules:
          - action:
              route:
                destination:
                  spec: { protocol: L7mpController }
